---
# tasks/main.yml

- name: Install Apache2 and PHP
  apt:
    name:
      - apache2
      - php
    state: present

- name: Ensure Apache2 service is running
  service:
    name: apache2
    state: started
    enabled: yes