plugin: aws_ec2
regions:
  - eu-west-3

filters:
  instance-state-name: running
  tag:Name: "vfc-*"

hostnames:
  - tag:Name
  - public-ip-address

keyed_groups:
  - key: tags.Role
    prefix: role

compose:
  ansible_host: public_ip_address 