name: Deploy high availability AWS infrastructure

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.1

      - name: Set up AWS credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: "1.13.4"

      - name: Terraform Init
        run: |
          cd Terraform
          terraform init

      - name: Terraform Plan
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          cd Terraform
          terraform validate
          terraform plan -var="aws_region=${{ secrets.AWS_REGION }}" -out=tfplan

      - name: Terraform Apply
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          cd Terraform
          terraform apply -var="aws_region=${{ secrets.AWS_REGION }}" -auto-approve tfplan

      - name: Terraform Output
        id: tf_output
        run: |
          cd Terraform
          ASG_IPS=$(terraform output -json asg_instance_ips | jq -r '.[]' | paste -sd " " -)
          echo "ASG_IPS=$ASG_IPS" >> $GITHUB_ENV

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Install Ansible AWS dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install ansible boto3 botocore

      - name: Debug inventory
        run: |
          cd Ansible
          ansible-inventory -i aws_ec2.yml --graph
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Run Ansible Playbook
        run: |
          cd Ansible
          ansible-playbook playbook.yml --user ubuntu
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
  
